# Generated by Django 4.0.6 on 2023-03-01 21:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_alter_item_date_created_alter_order_date_of_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.TextField(default=None, null=True, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 0, 50, 24, 345224), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 0, 50, 24, 346222), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateField(default=datetime.date(2023, 3, 2), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='unauthorised_order',
            name='date_of_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 0, 50, 24, 347219), verbose_name='date created'),
        ),
    ]
